;;; ci-deps.el --- Install aperture's dependencies for CI -*- lexical-binding: t -*-

;; SPDX-License-Identifier: GPL-3.0-or-later

;;; Commentary:

;; Run with `make deps'.  Installs vertico, consult and package-lint into
;; .deps/, then writes .deps.mk with the resulting `-L' flags.
;;
;; A makefile fragment rather than inline workflow steps, so CI runs the same
;; `make' targets a developer runs.
;;
;; local.mk is never touched: that file is the developer's own machine
;; configuration.  .deps.mk *appends* to DEPS, so having both is harmless and
;; either can be used alone.

;;; Code:

(require 'package)
(require 'cl-lib)

(defconst ci-deps-packages '(vertico consult package-lint)
  "Packages CI needs.

consult is a soft dependency of aperture but a hard one of the checks:
`aperture-consult.el' has to byte-compile against the real function it
advises.  Note that `make test' still runs with no dependencies at all --
see the Makefile, and invariant 5 in TODO.md.")

(defconst ci-deps-dir (expand-file-name ".deps" default-directory))

(defconst ci-deps-makefile (expand-file-name ".deps.mk" default-directory))

(defun ci-deps-load-dirs ()
  "Return every directory under `ci-deps-dir' holding Emacs Lisp.
Subdirectories matter: vertico keeps `vertico-buffer' -- which aperture
requires -- in an `extensions' directory that installing alone does not
put on the load path."
  (let (dirs)
    (dolist (dir (directory-files ci-deps-dir t "\\`[^.]"))
      (when (file-directory-p dir)
        (when (directory-files dir nil "\\.el\\'" t)
          (push dir dirs))
        (dolist (sub (directory-files dir t "\\`[^.]"))
          (when (and (file-directory-p sub)
                     (directory-files sub nil "\\.el\\'" t))
            (push sub dirs)))))
    (nreverse dirs)))

(defun ci-deps-install ()
  "Install `ci-deps-packages' and write `ci-deps-makefile'."
  (setq package-user-dir ci-deps-dir)
  (add-to-list 'package-archives
               '("melpa" . "https://melpa.org/packages/") t)
  (package-initialize)
  (package-refresh-contents)
  (dolist (pkg ci-deps-packages)
    (unless (package-installed-p pkg)
      (message "ci-deps: installing %s" pkg)
      (package-install pkg)))
  (let ((dirs (ci-deps-load-dirs)))
    (unless dirs
      (error "ci-deps: nothing installed under %s" ci-deps-dir))
    (with-temp-file ci-deps-makefile
      (insert "# Generated by dev/ci-deps.el -- do not edit, do not commit.\n"
              "# Appends to DEPS so a developer's local.mk still applies.\n"
              "DEPS += "
              (mapconcat (lambda (d) (concat "-L " d)) dirs " ")
              "\n"))
    (message "ci-deps: wrote %s with %d load path entries"
             ci-deps-makefile (length dirs))))

(ci-deps-install)

(provide 'ci-deps)
;;; ci-deps.el ends here
